### ISSUE TITLE
Add support for GB core

### ISSUE THREAD

**Issue by emillassen** [mattpannella/pocket_core_autoupdate_net#1]
The current version of the auto-updater (1.2.0) is missing support for the [GB core](https://github.com/spiritualized1997/openFPGA-GB-GBC/) by spiritualized1997.

**Comment by mattpannella** [comment]
yup, known issue. it'll fix fixed in the next release. thanks

**Comment by mattpannella** [comment]
v.1.3.0 was released and fixes this issue
