### ISSUE TITLE
Use an external API for getting the up-to-date list of cores

### ISSUE THREAD

**Issue by goronfreeman** [mattpannella/pocket_core_autoupdate_net#16]
I've noticed there are several tools in the community for updating Pocket cores. I have contributed to the [`update-pocket`](https://github.com/rivergillis/update-pocket) project, I'm aware of your project, and I know there is now a Windows application. Every time a new core is released, every project needs to update its own internal list of cores. It is my proposal that instead, we create a new API outside of these projects where the core list can be retrieved from.

We already have the great resource [`openfpga-cores-inventory`](https://github.com/joshcampbell191/openfpga-cores-inventory), so I suggest that we utilize that for hosting the API. This is another place that has to be independently updated every time a core is released, and is the best resource for members of the community to find the list of available cores. I already have the API put together in a local branch, ready to be put up as a PR, but for this to be successful, the developers of updater tools should all agree on a set JSON structure for the data.

I would love to get your feedback on this, and if there is a consensus in the community that this is a good idea, I'm more than happy to stand up the API myself.

**Comment by goronfreeman** [comment]
I added an issue to keep track of the discussion here: https://github.com/joshcampbell191/openfpga-cores-inventory#5

**Comment by goronfreeman** [comment]
Just a heads up, @mattpannella, we finally got all those API changes wrapped up and deployed. Let us know if there are any other tweaks we should consider making.

**Comment by mattpannella** [comment]
great! i'm doing some prep before I move over to using the api, but once I do if i have any questions/concerns/requests I'll let you guys know

**Comment by mattpannella** [comment]
ok, so I had a little more free time than expected this afternoon (its tough with a 4 year old lol) and i got up and running using the api instead of current json master file. I guess all i really need to know is, are guys gonna consider this v0 released? i don't want to release if you're still planning on making some tweaks that could potentially be breaking changes. the format right now works plenty fine for my needs. and this definitely isnt meant to rush haha. i can just hold back til its 100% final

**Comment by goronfreeman** [comment]
> ok, so I had a little more free time than expected this afternoon (its tough with a 4 year old lol) and i got up and running using the api instead of current json master file. I guess all i really need to know is, are guys gonna consider this v0 released? i don't want to release if you're still planning on making some tweaks that could potentially be breaking changes. the format right now works plenty fine for my needs. and this definitely isnt meant to rush haha. i can just hold back til its 100% final

Nice! Didn't expect you to be able to do that so quickly. Really, I think we were just waiting to make sure that it met everyone's needs. If it's working for you, I think we can probably call it stable. With what we've discussed, I can only think of cases where we're planning on adding on top of the existing structure, not changing it. Pinging @joshcampbell191 to make sure he feels the same way.

**Comment by mattpannella** [comment]
yeah additions are no issue. and really, the basic info is the bulk of what i need (repository name etc) so I can't see that changing. but i'm happy to wait as long as needed for more people to weigh in. 
@RetroDriven's utility uses my updater class, so that will be updated alongside mine. 
i could try and remember the other 1 or 2 people i've seen on discord that are maintaining their own update utilities to see if they wanna weigh in.

**Comment by goronfreeman** [comment]
Cool cool. That'd be great if you could reach out to the other people as well. I wasn't aware there were more tools than the ones I initially mentioned.

**Comment by goronfreeman** [comment]
Pinging @rivergillis for his input as well.

**Comment by mattpannella** [comment]
actually maybe it's only one. Keen on the classic gaming discord. but quickly looking at @rivergillis project, i think they may be the same person? haha
i just remember it was a python updater

**Comment by joshcampbell191** [comment]
> > ok, so I had a little more free time than expected this afternoon (its tough with a 4 year old lol) and i got up and running using the api instead of current json master file. I guess all i really need to know is, are guys gonna consider this v0 released? i don't want to release if you're still planning on making some tweaks that could potentially be breaking changes. the format right now works plenty fine for my needs. and this definitely isnt meant to rush haha. i can just hold back til its 100% final
> 
> Nice! Didn't expect you to be able to do that so quickly. Really, I think we were just waiting to make sure that it met everyone's needs. If it's working for you, I think we can probably call it stable. With what we've discussed, I can only think of cases where we're planning on adding on top of the existing structure, not changing it. Pinging @joshcampbell191 to make sure he feels the same way.

I think it's safe to say that the current API structure has all the fields required to support existing updaters and that we'd only add from here.
