### ISSUE TITLE
MacOS: ran, and now it's not generating files…?

### ISSUE THREAD

**Issue by remy** [mattpannella/pocket_core_autoupdate_net#2]
When I first ran this, I ran it from my /Downloads directory (wrong I know now), and it appeared to generate the directories.

So I removed these, and moved the `pocket_updater` to my `bin` path (locally to me) and moved `auto_updater.json` to the root of my sdcard.

I ran the program again (from the terminal), and it prints the output, but suggests cores are being skipped, and nothing changes on the sdcard.

I've also created a new directory on my machine, put the JSON file in there, and run - and it doesn't generate any new files.

(As an extra test I've managed to run it enough times for the logging to show I've hit the rate limit, but this was well after the attempts I've already made).

Any ideas?

<details>
<summary><strong>Full log here</strong></summary>
<pre>
Analogue Pocket Core Updater v1.2.0
Checking for updates...
Download master cores list file from github? (This will overwrite your current file) [y/n]:
yDownloading...
Download complete:
/Users/remy/bin/auto_update.json
Starting update process...
Starting Repo: openFPGA-GBA
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Up to date. Skipping core
Looking for BIOS
BIOS file already installed: gba_bios.bin
------------
Starting Repo: openFPGA-GB-GBC
v1.3.0 is the most recent release, checking local core...
local core found: v1.3.0
Up to date. Skipping core
Looking for BIOS
BIOS file already installed: gbc_bios.bin
------------
Starting Repo: PDP-1
v1.1.0 is the most recent release, checking local core...
local core found: v3.1.0
Up to date. Skipping core
------------
Starting Repo: Analogue_Pocket_Neogeo
Alpha_0.6.0_2022-15-08 is the most recent release, checking local core...
local core found: v0.6.0
Up to date. Skipping core
Looking for BIOS
BIOS file already installed: uni-bios_1_0.rom
BIOS file already installed: 000-lo.lo
------------
Starting Repo: openFPGA-SG1000
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Up to date. Skipping core
------------
Starting Repo: openFPGA-SMS
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Up to date. Skipping core
------------
Starting Repo: openFPGA-GG
v1.3.0 is the most recent release, checking local core...
local core found: v1.2.0
Updating core
Downloading file https://github.com/spiritualized1997/openFPGA-GG/releases/download/v1.3.0/Spiritualized_GG_1.3.0_2022_08_25.zip...
Extracting...
Installation complete.
------------
Starting Repo: analogue-pong
1.1.0 is the most recent release, checking local core...
local core found: v1.1.0
Up to date. Skipping core
------------
Starting Repo: openfpga-tecmo
v1.0 is the most recent release, checking local core...
local core found: v1.0.0
Up to date. Skipping core
------------
and now its done
</pre>
</details>

**Comment by mattpannella** [comment]
it's using a pretty crude method to detect the current directory. so you
need to literally put the executable on the sd card and run it. since it
just checks the directory that the executable is in, not where you're
running it from
I want to fix that eventually but it works for now haha

**Comment by mattpannella** [comment]
v1.4.0 let's you pass the install path in as a parameter so that should solve your problem

**Comment by mattpannella** [comment]
also the github rate limit resets after like a half hour so no worries
there
