### ISSUE TITLE
Error communicating with Github API. Response status code does not indicate success: 403 (rate limit exceeded).

### ISSUE THREAD

**Issue by jserodio** [mattpannella/pocket_core_autoupdate_net#21]
I was having some strange 404 errors and after removing some files and running it again now it just won't download anything else.

Error communicating with Github API.
Response status code does not indicate success: 403 (rate limit exceeded).

![image](https://user-images.githubusercontent.com/5813094/193448539-5f62cbff-e611-42fe-8dbd-942e171e48f9.png)

**Comment by jserodio** [comment]
Nevermind I just waited and started it again. It seems to be working again! thanks

**Comment by mattpannella** [comment]
there's a limit to how many times you can access the github api per hour. this will happen any time you run the updater multiple times in a row
two ways to get around it is either disable the cores you don't care about in settings or generate a personal access token on github and put it in your settings file(if you don't know what this means it's probably best to ignore it haha)
