### ISSUE TITLE
Boogerman cores MAC

### ISSUE THREAD

**Issue by Princepicklepants** [mattpannella/pocket_core_autoupdate_net#23]
None of the boogerman cores get the Roms for me on mac whilst all the other arcade cores are fine. Guessing it is what is and should just be done manually?

**Comment by mattpannella** [comment]
which version are you running

**Comment by Princepicklepants** [comment]
I’m now using the latest. But none of the releases have got the boogermann assets for me. 

they just say:

The SSL connection could not be established, see inner exception

after trying to download.

**Comment by Princepicklepants** [comment]
If helpful, here is the full update for boogeyman cores:


Starting Repo: arcade-gberet
0.1.1 is the most recent release, checking local core...
local core found: v0.1.0
Updating core
Downloading file https://github.com/opengateware/arcade-gberet/releases/download/0.1.1/boogermann.gberet_pocket-0.1.1.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-gberet/releases/download/0.1.1/boogermann.gberet_rom-recipes-0.1.1.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading gberet.rom
Uh oh something went wrong.
The SSL connection could not be established, see inner exception.
Starting Repo: arcade-xevious
0.1.0 is the most recent release, checking local core...
local core found: v0.1.0
Looking for Assets
Downloading battles2.rom
Uh oh something went wrong.
The SSL connection could not be established, see inner exception.

**Comment by mattpannella** [comment]
try deleting your pocket_updater_settings.json file and running it again

**Comment by Princepicklepants** [comment]
Still getting the same outcome, anything else I could try? 

by the way it works with everything else for me and it’s still super useful so don’t want to sound ungrateful for your work. Thank you!

**Comment by mattpannella** [comment]
haha no you dont sound that way at all! just trying to think of stuff you can try to troubleshoot it on your own since i'm at work and can't check it out myself til tonight.
what if you rename(dont delete it, this way you dont lose it haha) a rom for another core. does that also fail to re-download? 
just seems weird it would only be the boogermann ones since they all work the same way

**Comment by Princepicklepants** [comment]
Okay so I tried that and yes it couldn’t re download. So we recently got a new service provider for internet, which would have been after downloading the other cores. I just tethered off my phone instead just now and it all worked fine. So something to do with the network we are using that doesn’t like old Arcade games lol. Thanks for your help!
