### ISSUE TITLE
Always updates openFPGA-GG v1.3.0

### ISSUE THREAD

**Issue by johnwu** [mattpannella/pocket_core_autoupdate_net#26]
Running update 2.1, and noticed the updater always updates to openFPGA-GG v1.3.0 even after previously updated to v1.3.0

------------
Starting Repo: openFPGA-GG
v1.3.0 is the most recent release, checking local core...
local core found: v1.2.0
Updating core
Downloading file https://github.com/spiritualized1997/openFPGA-GG/releases/download/v1.3.0/Spiritualized_GG_1.3.0_2022_08_25.zip...
Extracting...
Installation complete.
------------

Not a show stopper, but just wanted to let you know in case it is a bug. 

Thanks for your work on this!

**Comment by mattpannella** [comment]
yeah known issue unfortunately. the gg core has the wrong version in the release (it's correctly tagged on GitHub) so it always triggers an update. you can fix it manually by editing Cores/spiritualized1997.GG/core.json and fix the version to be 1.3.0
