### ISSUE TITLE
Ask for permission to download Arcade ROMs

### ISSUE THREAD

**Issue by SuperPositiveP** [mattpannella/pocket_core_autoupdate_net#29]
Some of us have ISPs who will get angry at seeing us downloading this stuff or are in residency at a place that requires we use someone else's network and follow their rules.

The addition of a prompt that asks if it is okay for the updater to download ROM files before it does so would be greatly appreciated.

**Comment by SuperPositiveP** [comment]
At least add a warning to the readme or script, y'know? I appreciate the tool but sheesh.

**Comment by mattpannella** [comment]
not sure I can make it much clearer in the read me, it says in the very top of the readme, but I actually planned to give the option to disable downloading assets and never finished implementing it. there's a setting in the pocket_updater_settings.json file called `download_assets` that defaults to true but you can set to false. it just doesn't do anything currently but I can get that into the next release

**Comment by mattpannella** [comment]
wait nevermind, i did implement that. it should work now
