### ISSUE TITLE
Pre-releases should be opt-in, not opt-out

### ISSUE THREAD

**Issue by goronfreeman** [mattpannella/pocket_core_autoupdate_net#32]
See: joshcampbell191/openfpga-cores-inventory#18

I don't know whether or not @RetroDriven will need to handle this separately on his end as well.

**Comment by mattpannella** [comment]
2.4.0 sets the flag to false by default. but i rushed this out so people can use the option to preserve their Platforms directory.
still gotta come up with a system to do a 1 time update to flip all the existing trues to falses.

**Comment by mattpannella** [comment]
closing. defaulting the allow prerelease flag to false should be sufficient
