### ISSUE TITLE
Donkey Kong arcade roms not downloading

### ISSUE THREAD

**Issue by syltendo** [mattpannella/pocket_core_autoupdate_net#39]
Title says it all. When running the updater it doesn't download any roms for Eric Lewis' Donkey Kong arcade core. On my side anyways (tested on a Mac).

Thank you for your hard work!

**Comment by mattpannella** [comment]
hm, but the core downloaded? if it skipped the core and the rom, check your pocket_updater_settings.json file and make sure the ericlewis.DonkeyKong core has "allowPrerelease" set to true

**Comment by syltendo** [comment]
Got it. Thank you!
