### ISSUE TITLE
Updater fails on MacOS ARM unless Rosetta installed

### ISSUE THREAD

**Issue by rpetersnil** [mattpannella/pocket_core_autoupdate_net#46]
I ran the updater on my new ARM Mac laptop and got the following error (using zsh): 

"Bad CPU type in executable"

It turns out that Rosetta is no longer installed by default, and command line apps don't give a very good error if it is missing. To resolve the issue, I installed install Rosetta via: 

> softwareupdate –-install-rosetta

Ideally the updater would support ARM as well as x86-64 so others don't run into this.

**Comment by mattpannella** [comment]
oh wow i had no idea rosetta wasn't installed by default anymore. when did that happen?
i figured most people would have no idea what x86 vs arm even is, so i made the mac build target x86
i guess i can just start making builds for both. i was just trying to make it simple for non-technical people who have no idea what these things mean haha

**Comment by mattpannella** [comment]
just looked it up, apparently the first time you try to run an x86 app it prompts you to install rosetta. i guess i did that and dont remember. thanks for pointing this out (although i wonder why it doesn't prompt when running this app..)

**Comment by rpetersnil** [comment]
My Googling said that the prompt to install Rosetta only comes up for x86 *GUI* apps. CLI apps just give the above error.

**Comment by mattpannella** [comment]
annoying, but yeah that must explain it.
i can put an arm build up now, but the code that auto-detects updates is not going to work properly because its gonna pull down the x86 version. i can work on fixing that for the next release, though

**Comment by rpetersnil** [comment]
Ideally the Mac binary would be Universal (one binary to support both) like most are, but I didn't find the docs/options for this build system to see if that was supported for .Net apps. I can look into it if you want.

**Comment by mattpannella** [comment]
yeah i didnt see anything in microsoft's documentation either. i can look into it more

**Comment by mattpannella** [comment]
yeah dotnet cli doesn't natively support it, but i can try this out. no guarantees on a timeframe, but thanks for pointing this out. i honestly assumed rosetta was always enabled haha

https://www.kenmuse.com/blog/notarizing-dotnet-console-apps-for-macos/

**Comment by mattpannella** [comment]
ok my build process should be creating a universal binary as of 2.60
